sudo: required
dist: trusty
language: cpp
cache: apt

branches:
  only:
    - 'master'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y qt5-qmake qt5-default qtbase5-dev gcc-4.8 libqrencode-dev libzbar-dev libappindicator-dev

script:
  - qmake
  - make
